// generated by meshes/make_gartling_bfs_quad.py -- Gartling BFS, structured all-quad, wall-clustered
// nx 141 ny 70 ry 1.1
Point(1) = {0.000000, -0.500000, 0, 1.0};
Point(2) = {17.000000, -0.500000, 0, 1.0};
Point(3) = {17.000000, 0.000000, 0, 1.0};
Point(4) = {17.000000, 0.500000, 0, 1.0};
Point(5) = {0.000000, 0.500000, 0, 1.0};
Point(6) = {0.000000, 0.000000, 0, 1.0};
Line(1) = {1, 2};
Transfinite Curve {1} = 142;
Line(2) = {2, 3};
Transfinite Curve {2} = 36 Using Progression 1.100000;
Line(3) = {4, 3};
Transfinite Curve {3} = 36 Using Progression 1.100000;
Line(4) = {4, 5};
Transfinite Curve {4} = 142;
Line(5) = {5, 6};
Transfinite Curve {5} = 36 Using Progression 1.100000;
Line(6) = {1, 6};
Transfinite Curve {6} = 36 Using Progression 1.100000;
Curve Loop(1) = {1, 2, -3, 4, 5, -6};
Plane Surface(1) = {1};
Transfinite Surface {1} = {1, 2, 4, 5};
Recombine Surface {1};
Physical Surface("Fluid", 1) = {1};
Physical Curve("Inlet", 2) = {5};
Physical Curve("Outlet", 3) = {2, 3};
Physical Curve("Wall", 4) = {1, 4, 6};
