"""Butterfly O-grid for the Re 3900 cylinder LES (V3): all quads, wall cell ~0.003 D, near-wake cells 0.04 D
to x = 6 D, lateral extent 10 D (blockage 5%), outlet 20 D. Emits cylinder_re3900.geo and runs gmsh.
    python meshes/make_cylinder_re3900.py [--nt 72 --nr 58 --qr 1.05 --nv 44 --qv 1.06 --nw1 112 --nw2 75 --qw2 1.035]"""
import argparse, subprocess, os, numpy as np
ap = argparse.ArgumentParser(); ap.add_argument("--nt", type=int, default=72); ap.add_argument("--nr", type=int, default=58); ap.add_argument("--qr", type=float, default=1.05)
ap.add_argument("--nv", type=int, default=44); ap.add_argument("--qv", type=float, default=1.06); ap.add_argument("--nw1", type=int, default=112); ap.add_argument("--qw1", type=float, default=1.0)
ap.add_argument("--nw2", type=int, default=75); ap.add_argument("--qw2", type=float, default=1.035); ap.add_argument("--name", default="cylinder_re3900"); a = ap.parse_args()
L1, XIN, XOUT, XM, H = 1.5, 10.0, 20.0, 6.0, 10.0; c = 0.5 / np.sqrt(2)
P = {1: (0, 0), 2: (c, c), 3: (-c, c), 4: (-c, -c), 5: (c, -c), 6: (L1, L1), 7: (-L1, L1), 8: (-L1, -L1), 9: (L1, -L1),
     10: (-XIN, -H), 11: (-XIN, -L1), 12: (-XIN, L1), 13: (-XIN, H), 14: (-L1, H), 15: (L1, H), 16: (XM, H), 17: (XOUT, H),
     21: (-L1, -H), 20: (L1, -H), 22: (XM, -H), 23: (XOUT, -H), 24: (XM, L1), 25: (XM, -L1), 26: (XOUT, L1), 27: (XOUT, -L1)}
out = ["// generated by meshes/make_cylinder_re3900.py -- butterfly O-grid, Re 3900 cylinder LES", f"// nt {a.nt} nr {a.nr} qr {a.qr} nv {a.nv} qv {a.qv} nw1 {a.nw1} qw1 {a.qw1} nw2 {a.nw2} qw2 {a.qw2}"]
for k, (x, y) in P.items(): out.append(f"Point({k}) = {{{x:.9f}, {y:.9f}, 0, 1.0}};")
lines = {}; nl = [0]
def line(p, q, n, prog=1.0, arc=False):
    """directed line p -> q with n+1 points and cell growth `prog` from p to q; returns its id. Reuse if it exists (either direction)."""
    if (p, q) in lines: return lines[(p, q)]
    if (q, p) in lines: return -lines[(q, p)]
    nl[0] += 1; i = nl[0]; lines[(p, q)] = i
    out.append(f"Circle({i}) = {{{p}, 1, {q}}};" if arc else f"Line({i}) = {{{p}, {q}}};")
    out.append(f"Transfinite Curve {{{i}}} = {n + 1}" + (f" Using Progression {prog:.6f};" if abs(prog - 1) > 1e-12 else ";"))
    return i
NT, NR, QR, NV, QV, NW1, QW1, NW2, QW2 = a.nt, a.nr, a.qr, a.nv, a.qv, a.nw1, a.qw1, a.nw2, a.qw2
arcs = [line(2, 3, NT, arc=True), line(3, 4, NT, arc=True), line(4, 5, NT, arc=True), line(5, 2, NT, arc=True)]
rad = {p: line(p, q, NR, QR) for p, q in ((2, 6), (3, 7), (4, 8), (5, 9))}
sq = {(6, 7): line(6, 7, NT), (7, 8): line(7, 8, NT), (8, 9): line(8, 9, NT), (9, 6): line(9, 6, NT)}
# outward lines (growth away from the body)
line(7, 12, NV, QV); line(8, 11, NV, QV); line(7, 14, NV, QV); line(6, 15, NV, QV); line(8, 21, NV, QV); line(9, 20, NV, QV)
line(11, 12, NT); line(11, 10, NV, QV); line(12, 13, NV, QV); line(21, 10, NV, QV); line(14, 13, NV, QV); line(21, 20, NT); line(14, 15, NT)
# wake
line(6, 24, NW1, QW1); line(9, 25, NW1, QW1); line(15, 16, NW1, QW1); line(20, 22, NW1, QW1); line(25, 24, NT); line(24, 16, NV, QV); line(25, 22, NV, QV)
line(24, 26, NW2, QW2); line(25, 27, NW2, QW2); line(16, 17, NW2, QW2); line(22, 23, NW2, QW2); line(27, 26, NT); line(26, 17, NV, QV); line(27, 23, NV, QV)
ns = [0]
def surf(p1, p2, p3, p4):
    """transfinite quad block with corners p1..p4 counter-clockwise; the four lines must already exist."""
    ns[0] += 1; i = ns[0]
    def L(p, q): return lines[(p, q)] if (p, q) in lines else -lines[(q, p)]
    out.append(f"Curve Loop({i}) = {{{L(p1, p2)}, {L(p2, p3)}, {L(p3, p4)}, {L(p4, p1)}}};"); out.append(f"Plane Surface({i}) = {{{i}}};")
    out.append(f"Transfinite Surface {{{i}}} = {{{p1}, {p2}, {p3}, {p4}}};"); out.append(f"Recombine Surface {{{i}}};"); return i
S = [surf(2, 3, 7, 6), surf(3, 4, 8, 7), surf(4, 5, 9, 8), surf(5, 2, 6, 9),          # ring
     surf(10, 21, 8, 11), surf(11, 8, 7, 12), surf(12, 7, 14, 13),                     # inlet column
     surf(21, 20, 9, 8), surf(7, 6, 15, 14),                                            # centre column, below and above the ring
     surf(20, 22, 25, 9), surf(9, 25, 24, 6), surf(6, 24, 16, 15),                      # near wake
     surf(22, 23, 27, 25), surf(25, 27, 26, 24), surf(24, 26, 17, 16)]                  # far wake
def L(p, q): return abs(lines[(p, q)] if (p, q) in lines else lines[(q, p)])
out.append(f"Physical Surface(\"Fluid\", 1) = {{{', '.join(map(str, S))}}};")
out.append(f"Physical Curve(\"Inlet\", 2) = {{{L(11,10)}, {L(11,12)}, {L(12,13)}}};")
out.append(f"Physical Curve(\"Freestream\", 3) = {{{L(21,10)}, {L(21,20)}, {L(20,22)}, {L(22,23)}, {L(14,13)}, {L(14,15)}, {L(15,16)}, {L(16,17)}}};")
out.append(f"Physical Curve(\"Outlet\", 4) = {{{L(27,23)}, {L(27,26)}, {L(26,17)}}};")
out.append(f"Physical Curve(\"Cylinder\", 5) = {{{', '.join(map(str, arcs))}}};")
geo = f"meshes/{a.name}.geo"; open(geo, "w").write("\n".join(out) + "\n")
subprocess.run(["gmsh", "-2", "-format", "msh2", "-o", f"meshes/{a.name}.msh", geo, "-v", "2"], check=True)
import sys; sys.path.insert(0, ".")
from src.umesh import Mesh, read_gmsh22
nodes, cells, ctag, edges, etag, names = read_gmsh22(f"meshes/{a.name}.msh"); m = Mesh(nodes, cells, edges, etag, names)
inv = {v: k for k, v in names.items()}; bt = m.btag[m.bfaces]; wall = m.bfaces[bt == inv["Cylinder"]]; wo = m.owner[wall]; dn = np.hypot(*(m.fcentre[wall] - m.centroid[wo]).T)
print(f"{a.name}: {m.ncell} cells ({int((m.nvert == 3).sum())} triangles), wall faces {len(wall)}, wall cell height {2*dn.min():.4f}-{2*dn.max():.4f} D, wall arc {np.pi/len(wall):.4f} D, orth min {float(m.orth.min()):.3f}, "
      f"x {nodes[:, 0].min():.0f}..{nodes[:, 0].max():.0f}, |y| {nodes[:, 1].max():.0f}; boundary faces: " + ", ".join(f"{v} {int((bt == k).sum())}" for k, v in names.items() if k in bt))
