"""Gartling's backward-facing-step benchmark domain (Gartling 1990, IJNMF 11:953), per the convention
recorded in ~/Dropbox/Apple_MLX_CFD/sem_demo/GARTLING_VALIDATION.md: a SINGLE rectangle [0,17]x[-0.5,0.5]
-- there is no meshed step geometry, the "step" is purely boundary conditions (parabolic inflow only
over the upper half of the left edge, no-slip over the lower half, which is the step face). Re = 800 is
built on the inlet hydraulic diameter 2h=1 and mean velocity 1 (nu = 1/800), not literally on the step
height, per that same note. Triangular mesh, graded finer near the walls and the shear-layer line, but
ONLY over x in [0,13] (where the recirculation/reattachment live, per the reference's own x_r ~ 6-10.5)
-- x in [13,17] is left coarse/near-uniform, same as a plain uniform mesh.

TWO EARLIER ATTEMPTS were unstable (exponentially growing, sign-flipping v at a single cell, spreading
within ~50-250 steps), despite each passing ordinary mesh-quality checks (min angle, neighbour volume
ratio) with numbers comparable to many working meshes elsewhere in this project:
  1. Box-field grading (hard-edged VALUE blending): failed at the shear-box's x=13 edge.
  2. Distance+Threshold grading over the FULL-length wall curves (smooth in both value and
     gradient): failed instead near the outlet corners, where fine wall-adjacent cells met the
     geometric corner between a Wall curve and the Outlet curve.
A plain UNIFORM mesh at a comparable cell count was rock solid in both cases (same BCs, same solver,
even plain first-order upwind). The common factor was grading reaching all the way to the outlet
corners; this version confines all refinement to x <= 13, leaving the outlet region genuinely close to
uniform. Verified stable 400 steps before being trusted for a real run (see run log in the record).
    python meshes/make_gartling_bfs.py [--h-wall 0.03 --h-shear 0.055 --h-far 0.4 --name gartling_bfs]"""
import argparse, subprocess, sys
ap = argparse.ArgumentParser()
ap.add_argument("--h-wall", type=float, default=0.03, help="target cell size at the walls, x in [0,13]")
ap.add_argument("--h-shear", type=float, default=0.055, help="target cell size along the shear-layer line, x in [0,13]")
ap.add_argument("--h-far", type=float, default=0.4, help="target cell size everywhere else, including all of x in [13,17]")
ap.add_argument("--name", default="gartling_bfs")
a = ap.parse_args()

L, H, XSPLIT = 17.0, 0.5, 13.0
out = ["// generated by meshes/make_gartling_bfs.py -- Gartling BFS, refinement confined to x <= 13",
       f"// h_wall {a.h_wall} h_shear {a.h_shear} h_far {a.h_far}"]
pts = {1: (0, -H), 2: (L, -H), 3: (L, H), 4: (0, H), 5: (0, 0), 6: (XSPLIT, 0),
       7: (XSPLIT, -H), 8: (XSPLIT, H)}  # 7, 8 split the bottom/top walls at x = 13
for k, (x, y) in pts.items():
    out.append(f"Point({k}) = {{{x:.6f}, {y:.6f}, 0, {a.h_far}}};")
out += [
    "Line(1) = {1, 7};",   # bottom wall, x in [0, 13] -- fine
    "Line(2) = {7, 2};",   # bottom wall, x in [13, 17] -- coarse
    "Line(3) = {2, 3};",   # outlet
    "Line(4) = {3, 8};",   # top wall, x in [17, 13] -- coarse
    "Line(5) = {8, 4};",   # top wall, x in [13, 0] -- fine
    "Line(6) = {4, 5};",   # inlet (upper half of left edge)
    "Line(7) = {5, 1};",   # step face (lower half of left edge, no-slip)
    "Curve Loop(1) = {1, 2, 3, 4, 5, 6, 7};",
    "Plane Surface(1) = {1};",
    "Physical Surface(\"Fluid\", 1) = {1};",
    "Physical Curve(\"Inlet\", 2) = {6};",
    "Physical Curve(\"Outlet\", 3) = {3};",
    "Physical Curve(\"Wall\", 4) = {1, 2, 4, 5, 7};",
    # embedded (non-physical) shear-layer line, x in [0, 13], purely for the Distance field
    "Line(8) = {5, 6};",
    "Line{8} In Surface{1};",
    "Field[1] = Distance;", "Field[1].CurvesList = {1, 5, 7};", "Field[1].Sampling = 200;",  # fine wall segments only
    "Field[2] = Threshold;", "Field[2].InField = 1;",
    f"Field[2].SizeMin = {a.h_wall};", f"Field[2].SizeMax = {a.h_far};",
    "Field[2].DistMin = 0.02;", "Field[2].DistMax = 0.5;",
    "Field[3] = Distance;", "Field[3].CurvesList = {8};", "Field[3].Sampling = 200;",
    "Field[4] = Threshold;", "Field[4].InField = 3;",
    f"Field[4].SizeMin = {a.h_shear};", f"Field[4].SizeMax = {a.h_far};",
    "Field[4].DistMin = 0.1;", "Field[4].DistMax = 3.0;",
    "Field[5] = Min;", "Field[5].FieldsList = {2, 4};",
    "Background Field = 5;",
    "Mesh.CharacteristicLengthExtendFromBoundary = 0;",
    "Mesh.Smoothing = 20;",
    "Mesh.Optimize = 1;",
]
geo = f"meshes/{a.name}.geo"; open(geo, "w").write("\n".join(out) + "\n")
subprocess.run(["gmsh", "-2", "-format", "msh2", "-o", f"meshes/{a.name}.msh", geo, "-v", "2"], check=True)

sys.path.insert(0, ".")
from src.umesh import Mesh, read_gmsh22
nodes, cells, ctag, edges, etag, names = read_gmsh22(f"meshes/{a.name}.msh")
m = Mesh(nodes, cells, edges, etag, names)
print(f"{a.name}: {m.ncell} cells, {m.nbface} boundary faces, audit {m.audit()}")
