"""Gartling BFS domain (see make_gartling_bfs.py for the geometry/BC convention), this time an
all-quad STRUCTURED transfinite mesh instead of unstructured triangles: same single rectangle
[0,17]x[-0.5,0.5], same Inlet/Outlet/Wall tagging, but with explicit geometric clustering toward
BOTH walls (y = +-0.5) via a Progression on each half of the wall-normal direction, uniform in x.
A transfinite quad grid grades smoothly cell-to-cell by construction (a fixed ratio r per row), so it
does not reproduce the abrupt-transition instability found and fixed for the unstructured mesh in
skew_unstructured_literature.md section 69 -- verified by rerunning the same stability smoke test
before trusting it (see the record).
    python meshes/make_gartling_bfs_quad.py [--nx 141 --ny 70 --ry 1.10 --name gartling_bfs_quad]"""
import argparse, subprocess, sys
ap = argparse.ArgumentParser()
ap.add_argument("--nx", type=int, default=141, help="streamwise divisions (uniform)")
ap.add_argument("--ny", type=int, default=70, help="wall-normal divisions, TOTAL (split evenly, 35 per half)")
ap.add_argument("--ry", type=float, default=1.10, help="wall-normal growth ratio away from each wall")
ap.add_argument("--name", default="gartling_bfs_quad")
a = ap.parse_args()
assert a.ny % 2 == 0, "--ny must be even (split evenly top/bottom about y=0)"
nyh = a.ny // 2

L, H = 17.0, 0.5
out = ["// generated by meshes/make_gartling_bfs_quad.py -- Gartling BFS, structured all-quad, wall-clustered",
       f"// nx {a.nx} ny {a.ny} ry {a.ry}"]
pts = {1: (0, -H), 2: (L, -H), 3: (L, 0), 4: (L, H), 5: (0, H), 6: (0, 0)}
for k, (x, y) in pts.items():
    out.append(f"Point({k}) = {{{x:.6f}, {y:.6f}, 0, 1.0}};")
out += [
    # Lines defined with their FIRST point at a wall, so "Using Progression r" (r>1) puts the
    # smallest cell at that wall end and grows toward the centreline -- independent of how the
    # line is later referenced (+/-) in the Curve Loop.
    f"Line(1) = {{1, 2}};",              # bottom wall, P1(wall corner) -> P2(wall corner), uniform
    f"Transfinite Curve {{1}} = {a.nx + 1};",
    f"Line(2) = {{2, 3}};",              # outlet, lower half: P2(wall) -> P3(centre)
    f"Transfinite Curve {{2}} = {nyh + 1} Using Progression {a.ry:.6f};",
    f"Line(3) = {{4, 3}};",              # outlet, upper half, defined P4(wall) -> P3(centre) for progression
    f"Transfinite Curve {{3}} = {nyh + 1} Using Progression {a.ry:.6f};",
    f"Line(4) = {{4, 5}};",              # top wall, P4 -> P5, uniform (reverse of bottom's direction)
    f"Transfinite Curve {{4}} = {a.nx + 1};",
    f"Line(5) = {{5, 6}};",              # inlet, upper half: P5(wall) -> P6(centre)
    f"Transfinite Curve {{5}} = {nyh + 1} Using Progression {a.ry:.6f};",
    f"Line(6) = {{1, 6}};",              # step face, lower half, defined P1(wall) -> P6(centre)
    f"Transfinite Curve {{6}} = {nyh + 1} Using Progression {a.ry:.6f};",
    # closed CCW loop: P1->P2 (1), P2->P3 (2), P3->P4 (-3), P4->P5 (4), P5->P6 (5), P6->P1 (-6)
    "Curve Loop(1) = {1, 2, -3, 4, 5, -6};",
    "Plane Surface(1) = {1};",
    "Transfinite Surface {1} = {1, 2, 4, 5};",
    "Recombine Surface {1};",
    "Physical Surface(\"Fluid\", 1) = {1};",
    "Physical Curve(\"Inlet\", 2) = {5};",
    "Physical Curve(\"Outlet\", 3) = {2, 3};",
    "Physical Curve(\"Wall\", 4) = {1, 4, 6};",
]
geo = f"meshes/{a.name}.geo"; open(geo, "w").write("\n".join(out) + "\n")
subprocess.run(["gmsh", "-2", "-format", "msh2", "-o", f"meshes/{a.name}.msh", geo, "-v", "2"], check=True)

sys.path.insert(0, ".")
from src.umesh import Mesh, read_gmsh22
nodes, cells, ctag, edges, etag, names = read_gmsh22(f"meshes/{a.name}.msh")
m = Mesh(nodes, cells, edges, etag, names)
import numpy as np
print(f"{a.name}: {m.ncell} cells ({int((m.nvert==4).sum())} quads), {m.nbface} boundary faces, audit {m.audit()}")
h = np.sqrt(m.vol)
print(f"cell size: min {h.min():.5f}  max {h.max():.5f}")
