"""Gartling BFS, all-quad, SAME wall-normal clustering as make_gartling_bfs_quad.py (r=1.10 toward
both walls, Ny=70), but now ALSO graded in x: uniform-fine (dx~0.055, matching the triangular mesh's
own h_shear from sections 69-70 almost exactly) over x in [0,13] -- the recirculation/reattachment
region -- then graded coarser from x=13 to the outlet at x=17. This is the direct, isolating test for
section 73's hypothesis: the quad mesh's sustained downstream oscillation (uniform streamwise dx=0.121
everywhere) might be an under-resolved-STREAMWISE artifact, since the triangular mesh that DID reach a
genuine steady state had exactly this x in [0,13] fine / x in [13,17] coarse profile, just without the
wall clustering. Two conformal transfinite quad blocks sharing one interior seam line at x=13 (same Ny
structure in both, so the seam is a plain interior interface, not a graded discontinuity).
    python meshes/make_gartling_bfs_quad_xrefine.py [--nx-a 236 --nx-b 30 --ny 70 --ry 1.10 --rxb 1.08]"""
import argparse, subprocess, sys
ap = argparse.ArgumentParser()
ap.add_argument("--nx-a", type=int, default=236, help="streamwise divisions, x in [0,13] (uniform, dx~0.055)")
ap.add_argument("--nx-b", type=int, default=30, help="streamwise divisions, x in [13,17] (graded, fine at x=13)")
ap.add_argument("--rxb", type=float, default=1.08, help="streamwise growth ratio in [13,17], away from x=13")
ap.add_argument("--ny", type=int, default=70, help="wall-normal divisions, TOTAL (split evenly, 35 per half)")
ap.add_argument("--ry", type=float, default=1.10, help="wall-normal growth ratio away from each wall")
ap.add_argument("--name", default="gartling_bfs_quad_xrefine")
a = ap.parse_args()
assert a.ny % 2 == 0
nyh = a.ny // 2
XSEAM, L, H = 13.0, 17.0, 0.5

out = ["// generated by meshes/make_gartling_bfs_quad_xrefine.py -- two conformal transfinite quad blocks",
       f"// nx_a {a.nx_a} nx_b {a.nx_b} rxb {a.rxb} ny {a.ny} ry {a.ry}"]
pts = {1: (0, -H), 2: (XSEAM, -H), 3: (L, -H), 4: (L, H), 5: (XSEAM, H), 6: (0, H), 7: (0, 0), 8: (XSEAM, 0), 9: (L, 0)}
for k, (x, y) in pts.items():
    out.append(f"Point({k}) = {{{x:.6f}, {y:.6f}, 0, 1.0}};")

def tc(i, p, q, n, prog=None):
    out.append(f"Line({i}) = {{{p}, {q}}};")
    tail = f" Using Progression {prog:.6f};" if prog else ";"
    out.append(f"Transfinite Curve {{{i}}} = {n + 1}{tail}")

tc(1, 1, 2, a.nx_a)                   # bottom_A: P1->P2, uniform
tc(2, 2, 8, nyh, a.ry)                # seam_lo: P2(wall)->P8(centre)
tc(3, 5, 8, nyh, a.ry)                # seam_hi: P5(wall)->P8(centre)
tc(4, 5, 6, a.nx_a)                   # top_A: P5->P6, uniform
tc(5, 6, 7, nyh, a.ry)                # inlet: P6(wall)->P7(centre)
tc(6, 1, 7, nyh, a.ry)                # step: P1(wall)->P7(centre)
out += [
    "Curve Loop(1) = {1, 2, -3, 4, 5, -6};",
    "Plane Surface(1) = {1};",
    "Transfinite Surface {1} = {1, 2, 5, 6};",
    "Recombine Surface {1};",
]
tc(7, 2, 3, a.nx_b, a.rxb)            # bottom_B: P2(fine, x13)->P3(coarse, x17)
tc(8, 3, 9, nyh, a.ry)                # outlet_lo: P3(wall)->P9(centre)
tc(9, 4, 9, nyh, a.ry)                # outlet_hi: P4(wall)->P9(centre)
tc(10, 5, 4, a.nx_b, a.rxb)           # top_B: P5(fine, x13)->P4(coarse, x17)
out += [
    "Curve Loop(2) = {7, 8, -9, -10, 3, -2};",
    "Plane Surface(2) = {2};",
    "Transfinite Surface {2} = {2, 3, 4, 5};",
    "Recombine Surface {2};",
    "Physical Surface(\"Fluid\", 1) = {1, 2};",
    "Physical Curve(\"Inlet\", 2) = {5};",
    "Physical Curve(\"Outlet\", 3) = {8, 9};",
    "Physical Curve(\"Wall\", 4) = {1, 4, 6, 7, 10};",
]
geo = f"meshes/{a.name}.geo"; open(geo, "w").write("\n".join(out) + "\n")
subprocess.run(["gmsh", "-2", "-format", "msh2", "-o", f"meshes/{a.name}.msh", geo, "-v", "2"], check=True)

sys.path.insert(0, ".")
from src.umesh import Mesh, read_gmsh22
import numpy as np
nodes, cells, ctag, edges, etag, names = read_gmsh22(f"meshes/{a.name}.msh")
m = Mesh(nodes, cells, edges, etag, names)
print(f"{a.name}: {m.ncell} cells ({int((m.nvert==4).sum())} quads), {m.nbface} boundary faces, audit {m.audit()}")
h = np.sqrt(m.vol)
print(f"cell size: min {h.min():.5f}  max {h.max():.5f}")
# seam check: cells just left/right of x=13 should have comparable size (no abrupt jump)
near_seam = np.abs(m.centroid[:, 0] - XSEAM) < 0.1
print(f"near-seam (|x-13|<0.1) cell size: min {h[near_seam].min():.5f} max {h[near_seam].max():.5f} ratio {h[near_seam].max()/h[near_seam].min():.2f}")
